name: Test and Deploy

on: 
  push:
    branches:
      - master
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        APP_NAME: ${{ 'flatwarming-1' }}
      run: |
        heroku container:login
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME  

